# Informations générales sur ton portfolio
title: "Elfried KINZOUN S.D"
description: "Portfolio de projets hebdomadaires en vision par ordinateur et IA."
logo: assets/im1.jpeg
show_downloads: true
theme: jekyll-theme-minimal

# Informations sur toi
author:
  name: "Elfried Steve David KINZOUN"
  email: "ekfriedkinzoun@gmail.com"
  description: "Je suis passionné par la robotique et l'intelligence artificielle. Je suis Béninois."

# Réseaux sociaux
social:
  github: "https://github.com/elfried96"
  linkedin: "https://linkedin.com/in/tonpseudo"
  twitter: "https://twitter.com/tonpseudo"
